# The address to bind to.
# Using a reverse proxy is recommended, because this application will not work over insecure HTTP.
bind_addr='127.0.0.1:2639'
# The path at which this server is reachable.
# Only relevant if you’re using a reverse proxy.
# If you set this parameter, you should *not* rewrite the URL in your reverse proxy.
base_path='/'
# Path to the the sqlite database file.
database='aof.db'
# The private key used for session cookies.
# Arbitrary string, but must be at least 32 bytes.
private_key=''
